v1.3

diff --git a/Source_Code/RedPitaya_GenApp_Offline/Makefile b/Source_Code/RedPitaya_GenApp_Offline/Makefile
--- a/Source_Code/RedPitaya_GenApp_Offline/Makefile
+++ b/Source_Code/RedPitaya_GenApp_Offline/Makefile
@@ -1,51 +1,45 @@
-# Directories
 BUILD_DIR = build
 SRC_DIR = src
 INCLUDE_DIR = include
 GEN_FILES_DIR = gen_files
 
-# Executable name
 EXECUTABLE = $(BUILD_DIR)/gen_app
 
-# Source and object files
-SRC_FILES = $(wildcard $(SRC_DIR)/*.cpp)
-OBJ_FILES = $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/%.o, $(SRC_FILES))
+SRC_FILES = $(shell find $(SRC_DIR) -name '*.cpp')
+OBJ_FILES = $(patsubst $(SRC_DIR)/%, $(BUILD_DIR)/%, $(SRC_FILES:.cpp=.o))
 
-# Compiler and flags
 CXX = g++
 CXXFLAGS = -std=c++17 -Wall -pedantic -I$(INCLUDE_DIR) `pkg-config --cflags gtkmm-3.0`
 LDFLAGS = `pkg-config --libs gtkmm-3.0` -lstdc++fs -lssh
 
-# Main target: clean, build and run
 all: clean appbuild run
 
-# Create build directory and copy gen_files
 $(BUILD_DIR):
 	@echo "Creating build directory..."
 	@mkdir -p $(BUILD_DIR)
-	@echo "Copying gen_files..."
+	@if [ ! -d $(GEN_FILES_DIR) ]; then \
+		echo "Error: $(GEN_FILES_DIR) folder not found. Please ensure it exists."; \
+		exit 1; \
+	fi
+	@echo "Copying gen_files into build/..."
 	@cp -r $(GEN_FILES_DIR) $(BUILD_DIR)
 
-# Compile source files into object files
 $(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
 	@echo "Compiling $<..."
+	@mkdir -p $(dir $@)
 	@$(CXX) $(CXXFLAGS) -c $< -o $@
 
-# Separate build target to avoid conflict with $(BUILD_DIR)
 appbuild: $(BUILD_DIR) $(EXECUTABLE)
 
-# Link object files to create the executable
 $(EXECUTABLE): $(OBJ_FILES)
 	@echo "Linking $(EXECUTABLE)..."
 	@$(CXX) $(OBJ_FILES) -o $(EXECUTABLE) $(LDFLAGS)
 	@echo "The app has been generated in $(BUILD_DIR)."
 
-# Run the app
 run:
 	@echo "Running application..."
 	@./$(EXECUTABLE)
 
-# Clean target
 clean:
 	@echo "Cleaning up generated files..."
 	@rm -rf $(BUILD_DIR)
